In [1]:
import wannierberri as wberri
import numpy as np


.::    .   .::: .:::::::.  :::.    :::.:::.    :::. :::.,::::::  :::::::..       :::::::.  .,::::::  :::::::..   :::::::..   :::
';;,  ;;  ;;;' '  ;;`;;  ` `;;;;,  `;;;`;;;;,  `;;; ;;;;;;;''''  ;;;;``;;;;       ;;;'';;' ;;;;''''  ;;;;``;;;;  ;;;;``;;;;  ;;;
 '[[, [[, [['    ,[[ '[[,    [[[[[. '[[  [[[[[. '[[ [[[ [[cccc    [[[,/[[['       [[[__[[\. [[cccc    [[[,/[[['   [[[,/[[['  [[[
   Y$c$$$c$P    c$$$cc$$$c   $$$ "Y$c$$  $$$ "Y$c$$ $$$ $$""""    $$$$$$c         $$""""Y$$ $$""""    $$$$$$c     $$$$$$c    $$$
    "88"888      888   888,  888    Y88  888    Y88 888 888oo,__  888b "88bo,    _88o,,od8P 888oo,__  888b "88bo, 888b "88bo,888
     "M "M"      YMM   ""`   MMM     YM  MMM     YM MMM """"YUMMM MMMM   "W"     ""YUMMMP"  """"YUMMM MMMM   "W"  MMMM   "W" MMM

a.k.a. Wannier19
                  __                     ___                  
        |_       (_  |_  _  _   _   _     |   _ .  _ |  .  _  
        |_) \/   __) |_ (- |_) (_| | )    |  _) | |  |( | | ) 
            /     

In [2]:
system=wberri.System_tb('Fe_tb.dat',getAA=True)

reading TB file Fe_tb.dat ( written on 25Oct2019 at 21:17:00 )
[]
Number of wannier functions: 18
Number of R points: 597
Minimal Number of K points: [13 13 13]
Real-space lattice:
 [[ 1.4349963  1.4349963  1.4349963]
 [-1.4349963  1.4349963  1.4349963]
 [-1.4349963 -1.4349963  1.4349963]]
Reading the system from Fe_tb.dat finished successfully


In [3]:
generators = ['Inversion','C4z','TimeReversal*C2x']
system.set_symmetry(generators)

[<wannierberri.symmetry.Symmetry object at 0x7f5e61530f10>, <wannierberri.symmetry.Symmetry object at 0x7f5e61530750>, <wannierberri.symmetry.Symmetry object at 0x7f5e61530c90>]


In [4]:
grid=wberri.Grid(system,length=100)

determining grids from NK=None (<class 'NoneType'>), NKdiv=None (<class 'NoneType'>), NKFFT=None (<class 'NoneType'>)
length=100 was converted into NK=[49 49 49]
Minimal symmetric FFT grid :  [13 13 13]


In [ ]:
wberri.integrate(system, grid,
            Efermi=np.linspace(12.,13.,1001),
            smearEf=10, # 10K
            quantities=["ahc","dos","cumdos"],
            numproc=16,
            adpt_num_iter=10,
            fout_name="Fe")


Integrating the following qantities: ahc, dos, cumdos

using NKdiv=[4 4 4], NKFFT=[13 13 13], NKtot=[52 52 52]
generating K_list
Excluding symmetry-equivalent K-points
Done. Excluded  51 K-points in 0.21919846534729004 sec
Done, sum of weights:1.0
iteration 0 - 13 points. New points are:
 K-point 0 : coord in rec.lattice = [  -0.500000  ,  -0.500000 ,   -0.500000 ], refinement level:0, dK=[0.25 0.25 0.25]  
 K-point 1 : coord in rec.lattice = [  -0.500000  ,  -0.250000 ,   -0.500000 ], refinement level:0, dK=[0.25 0.25 0.25]  
 K-point 2 : coord in rec.lattice = [  -0.500000  ,   0.000000 ,   -0.500000 ], refinement level:0, dK=[0.25 0.25 0.25]  
 K-point 3 : coord in rec.lattice = [  -0.500000  ,   0.000000 ,   -0.250000 ], refinement level:0, dK=[0.25 0.25 0.25]  
 K-point 4 : coord in rec.lattice = [  -0.250000  ,  -0.500000 ,   -0.250000 ], refinement level:0, dK=[0.25 0.25 0.25]  
 K-point 5 : coord in rec.lattice = [  -0.250000  ,  -0.250000 ,   -0.250000 ], refinement level:0, 

In [ ]:
wberri.tabulate(system, grid,
             quantities=["berry"],
             fout_name="Fe",
             numproc=16,
             ibands=np.arange(4,10),
             Ef0=12.6)